# Metadata
title: "Proyek Klasifikasi Tingkat Kehadiran Sekolah"
author: "Kelompok 01 - Faisal, Wiwin, Rizki"

# Konfigurasi GitHub Pages
html_baseurl: "/kelompok-01/"
use_directory_urls: false

# Tombol Peluncuran
launch_buttons:
  notebook_interface: jupyterlab
