# Pengaturan Judul & Author
title: "Proyek Klasifikasi Tingkat Kehadiran Sekolah"
author: "Faisal Graha Twofaz, Wiwin Pasaribu, Rizki Ramadhan Lubis, Fajar Aditya Pratama"
launch_buttons:
  notebook_interface: jupyterlab  # Tombol open di JupyterLab
